version: 2.1

executors:
  ubuntu-18_04:
    docker:
    - image: ubuntu:bionic-20220427

commands:
  install-base-linux:
    parameters:
      extra:
        type: string
    steps:
    - run:
        name: Update apt and install base packages
        command: |
          apt update
          apt install -y git << parameters.extra >>

  install-gcc-4_8:
    steps:
    - run:
        name: Install GCC 4.8
        # For some reason, CMake needs a working C compiler, so provice CC as
        # well for the case when default gcc isn't installed.
        command: |
          apt install -y g++-4.8
          echo 'export CC=gcc-4.8' >> $BASH_ENV
          echo 'export CXX=g++-4.8' >> $BASH_ENV

jobs:
  linux:
    executor: ubuntu-18_04
    steps:
    - install-base-linux:
        # heh
        extra: time
    - install-gcc-4_8
    - checkout
    - run:
        # TODO add testing of C++17, C++20 features once such compiler is here
        # TODO test growable array sanitizer annotations on a compiler that
        #   actually has __sanitizer_annotate_contiguous_container
        # TODO test also Math GLM and Eigen opt-in
        name: Build all singles
        command: |
          export COMPILE="time g++-4.8 -std=c++11 -Wall -Wextra -pedantic"

          cd test

          # First page in the compiler so the following measurements are less wild
          echo "int main() {}" | $COMPILE -x c++ - && ./a.out

          $COMPILE CorradeArrayView.cpp
          ./a.out
          $COMPILE CorradeArrayView.cpp -DCORRADE_ARRAYVIEW_STL_COMPATIBILITY
          ./a.out
          $COMPILE CorradeStridedArrayView.cpp
          ./a.out
          $COMPILE CorradeArray.cpp
          ./a.out
          $COMPILE CorradeGrowableArray.cpp
          ./a.out
          $COMPILE CorradeGrowableArray.cpp -fsanitize=address -DCORRADE_CONTAINERS_NO_SANITIZER_ANNOTATIONS
          ./a.out
          $COMPILE CorradeEnumSet.cpp
          ./a.out
          $COMPILE CorradeFunction.cpp
          ./a.out
          $COMPILE CorradeOptional.cpp
          ./a.out
          $COMPILE CorradePair.cpp
          ./a.out
          $COMPILE CorradePair.cpp -DCORRADE_PAIR_STL_COMPATIBILITY
          ./a.out
          $COMPILE CorradePointer.cpp
          ./a.out
          $COMPILE CorradePointer.cpp -DCORRADE_POINTER_STL_COMPATIBILITY
          ./a.out
          $COMPILE CorradeReference.cpp
          ./a.out
          $COMPILE CorradeReference.cpp -DCORRADE_REFERENCE_STL_COMPATIBILITY
          ./a.out
          $COMPILE CorradeScopeGuard.cpp
          ./a.out
          $COMPILE CorradeString.cpp
          ./a.out
          $COMPILE CorradeString.cpp -DCORRADE_STRING_STL_COMPATIBILITY
          ./a.out
          $COMPILE CorradeString.cpp -DCORRADE_NO_CPU_RUNTIME_DISPATCH
          ./a.out
          $COMPILE CorradeString.cpp -DCORRADE_CPU_USE_IFUNC
          ./a.out
          $COMPILE CorradeTriple.cpp
          ./a.out
          $COMPILE CorradeTriple.cpp -DCORRADE_TRIPLE_STL_COMPATIBILITY
          ./a.out
          $COMPILE CorradeStlForwardArray.cpp
          ./a.out
          $COMPILE CorradeStlForwardString.cpp
          ./a.out
          $COMPILE CorradeStlForwardTuple.cpp
          ./a.out
          $COMPILE CorradeStlForwardVector.cpp
          ./a.out
          $COMPILE CorradeStlMath.cpp
          ./a.out
          $COMPILE CorradeCpu.cpp
          ./a.out
          $COMPILE CorradeCpu.cpp -DCORRADE_CPU_USE_IFUNC
          ./a.out
          $COMPILE MagnumMath.cpp
          ./a.out
          $COMPILE MagnumMath.cpp -DMAGNUM_MATH_STL_COMPATIBILITY
          ./a.out

workflows:
  version: 2
  build:
    jobs:
    - linux
